server:
  port: 8500
  servlet:
    context-path: /sso

spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

security:
  oauth2:
    resource:
      jwt:
        key-value: yxsnb


